menu:
    Blog: /
    Archive: /archives/
    Category: /category/
    Friends: /link/
    GitHub: https://github.com/weremexii
    Rss: /atom.xml
    

favicon: favicon.png
logo: favicon.png
avatar: favicon.png
# Comment
# e.g disqus: achjqz
disqus:

gitalk:
    on: false
    clientID: 
    clientSecret: 
    owner:
    admin:
    repo:       

# Analytics
ga: G-HDFY1XPH41

# Copyright Infomation
startyear: 2020
